name: Publish to Nuget

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check release validity
        run: sh .github/scripts/check-release.sh
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.101
      - name: Publish
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Meilisearch/Meilisearch.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
